AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gym Integrator – Etap 1 (prod-ready)

Parameters:
  DevMode:
    Type: String
  LangDefault:
    Type: String

  TwilioAccountSid:
    Type: String
  TwilioAuthToken:
    Type: String
  TwilioMessagingSid:
    Type: String
    Default: ""      
  TwilioWhatsappNumber:
    Type: String

  OpenAiApiKey:
    Type: String
  LlmModel:
    Type: String

  PgBaseUrl:
    Type: String
  PgClientId:
    Type: String
  PgClientSecret:
    Type: String

  JiraUrl:
    Type: String
  JiraToken:
    Type: String
  JiraProjectKey:
    Type: String
    
Globals:
  Function:
    Runtime: python3.11
    Timeout: 25
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        PYTHONPATH: /var/task/src
        DEV_MODE:           !Ref DevMode
        LANG_DEFAULT:       !Ref LangDefault

        TWILIO_ACCOUNT_SID:     !Ref TwilioAccountSid 
        TWILIO_AUTH_TOKEN:      !Ref TwilioAuthToken
        TWILIO_MESSAGING_SID:   !Ref TwilioMessagingSid
        TWILIO_WHATSAPP_NUMBER: !Ref TwilioWhatsappNumber

        OPENAI_API_KEY:  !Ref OpenAiApiKey
        LLM_MODEL:       !Ref LlmModel

        PG_BASE_URL:      !Ref PgBaseUrl
        PG_CLIENT_ID:     !Ref PgClientId
        PG_CLIENT_SECRET: !Ref PgClientSecret

        JIRA_URL:         !Ref JiraUrl
        JIRA_TOKEN:       !Ref JiraToken
        JIRA_PROJECT_KEY: !Ref JiraProjectKey
        
        DDB_TABLE_TENANTS: !Sub 'Tenants-${AWS::StackName}'
        DDB_TABLE_CONVERSATIONS: !Sub 'Conversations-${AWS::StackName}'
        DDB_TABLE_MESSAGES:      !Sub 'Messages-${AWS::StackName}'
        DDB_TABLE_TEMPLATES:      !Sub 'Templates-${AWS::StackName}'
        DDB_TABLE_CAMPAIGNS:     !Sub 'Campaigns-${AWS::StackName}'
        DDB_TABLE_CONSENTS:      !Sub 'Consents-${AWS::StackName}'
        DDB_TABLE_INTENTS_STATS: !Sub 'IntentsStats-${AWS::StackName}'
        DDB_TABLE_MEMBERS_INDEX: !Sub 'MembersIndex-${AWS::StackName}'
        DDB_TABLE_LEADS:          !Sub 'Leads-${AWS::StackName}'
        
        KB_BUCKET: !Ref KnowledgeBaseBucket
        
        CAMPAIGN_SEND_FROM: "09:00"
        CAMPAIGN_SEND_TO: "20:00"
    

Resources:
  InboundEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'inbound-events-${AWS::StackName}'
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt InboundDLQ.Arn
        maxReceiveCount: 5
  InboundDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'inbound-events-${AWS::StackName}-dlq'

  OutboundQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'outbound-messages-${AWS::StackName}'
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OutboundDLQ.Arn
        maxReceiveCount: 5
  OutboundDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'outbound-messages-${AWS::StackName}-dlq'

  Tenants:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Tenants-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenant_id
          AttributeType: S
      KeySchema:
        - AttributeName: tenant_id
          KeyType: HASH

  Conversations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Conversations-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  Messages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Messages-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  Templates:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Templates-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  Campaigns:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Campaigns-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  Consents:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Consents-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  IntentsStats:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'IntentsStats-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
  
  Leads:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Leads-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
          
  MembersIndex:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'MembersIndex-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-kb-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  InboundWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'inbound-webhook-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/inbound_webhook/handler.lambda_handler
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt InboundEventsQueue.QueueName
        - DynamoDBCrudPolicy:             
            TableName: !Ref IntentsStats
      Environment:
        Variables:
          InboundEventsQueueUrl: !Ref InboundEventsQueue
          LOCALSTACK_ENDPOINT: ""         
          TwilioAccountSid: ""
          TwilioAuthToken: ""
          TWILIO_FROM: ""
          TWILIO_MESSAGING_SID: ""
          TWILIO_WHATSAPP_NUMBER: ""
      Events:
        Api:
          Type: Api
          Properties:
            Path: /webhooks/twilio
            Method: post

  MessageRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'message-router-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/message_router/handler.lambda_handler
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt InboundEventsQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OutboundQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref Messages
        - DynamoDBCrudPolicy:
            TableName: !Ref Conversations
        - DynamoDBCrudPolicy:
            TableName: !Ref Leads 
        - DynamoDBReadPolicy:
            TableName: !Ref Templates
        - DynamoDBReadPolicy:
            TableName: !Ref Tenants
        - S3ReadPolicy:
            BucketName: !Ref KnowledgeBaseBucket
      Environment:
        Variables:
          OutboundQueueUrl: !Ref OutboundQueue      
          TwilioAccountSid: ""
          TwilioAuthToken: ""
          TWILIO_FROM: ""
          TWILIO_MESSAGING_SID: ""
          TWILIO_WHATSAPP_NUMBER: ""
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InboundEventsQueue.Arn
            BatchSize: 5

  OutboundSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'outbound-sender-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/outbound_sender/handler.lambda_handler
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt OutboundQueue.QueueName      
      Environment:
        Variables:    
          TwilioAccountSid: ""
          TwilioAuthToken: ""
          TWILIO_FROM: ""
          TWILIO_MESSAGING_SID: ""
          TWILIO_WHATSAPP_NUMBER: ""
          WebOutboundEventsQueueUrl: !Ref OutboundQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OutboundQueue.Arn
            BatchSize: 5

  CampaignRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'campaign-runner-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/campaign_runner/handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Campaigns
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OutboundQueue.QueueName 
        - DynamoDBReadPolicy:
            TableName: !Ref Consents
      Environment:
        Variables:
          OutboundQueueUrl: !Ref OutboundQueue
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

  HousekeepingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'housekeeping-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/housekeeping/handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Messages
        - DynamoDBCrudPolicy:
            TableName: !Ref Conversations
        - DynamoDBCrudPolicy:  
            TableName: !Ref IntentsStats

  PgReservationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'pg-reservations-${AWS::StackName}'
      CodeUri: .
      Handler: src/lambdas/pg_reservations/handler.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/pg/test
            Method: post
            
  WebWidgetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambdas/web_widget/handler.lambda_handler
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              Fn::GetAtt:
                - InboundEventsQueue
                - QueueName
      Environment:
        Variables:
          InboundEventsQueueUrl:
            Ref: InboundEventsQueue
      Events:
        Api:
          Type: Api
          Properties:
            Path: /web/widget
            Method: post
    Metadata:
      SamResourceId: WebWidgetFunction
      
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: health-${AWS::StackName}
      CodeUri: src
      Handler: src/lambdas/health/handler.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /health
            Method: get
    Metadata:
      SamResourceId: HealthFunction


Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhooks/twilio'
  PgTestUrl:
    Description: API Gateway endpoint URL for PerfectGym manual test
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/pg/test'
